### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by hardy-ethan**
- Separated declarations and definitions into corresponding header and source files
- Moved member variables to private in favor of getters and setters
- Replaced auto ... -> return type syntax
- Assigned const qualifier where applicable
- Added .gitignore

Closes [@1](https://github.com/umigv/nav_stack/issues/1)

### CODE REVIEW

**Comment by hardy-ethan** [comment]
@kjdih2 not sure how you guys were testing this so plz lmk and/or pull and test

**Comment by 978-9-17-637879-3** [comment]
Closes @1

**Review by kjdih2 — APPROVED** [review]
It looks good.

**Comment by hardy-ethan** [comment]
no kizzy

**Pull request merged**
